# Generated by Django 3.0.6 on 2020-05-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=255)),
                ('avatar_url', models.TextField()),
            ],
        ),
    ]
